GO
USE [GD1C2014]

DROP TABLE STR_NOMBRE_GRUPO.CLIENTE
DROP TABLE STR_NOMBRE_GRUPO.EMPRESA
DROP TABLE STR_NOMBRE_GRUPO.ROL_FUNCIONALIDAD
DROP TABLE STR_NOMBRE_GRUPO.USUARIO_ROL
DROP TABLE STR_NOMBRE_GRUPO.FUNCIONALIDAD
DROP TABLE STR_NOMBRE_GRUPO.ROL
DROP TABLE STR_NOMBRE_GRUPO.USUARIO
DROP SCHEMA STR_NOMBRE_GRUPO