using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace FrbaCommerce.Historial_Cliente
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            // TODO: esta línea de código carga datos en la tabla 'gD1C2014DataSet1.USUARIO' Puede moverla o quitarla según sea necesario.
            this.uSUARIOTableAdapter.Fill(this.gD1C2014DataSet1.USUARIO);

        }
    }
}

/*-- Calificaciones de ventas realizadas
SELECT USU_USERNAME,PUB_ID, PUB_FECHA_FINALIZACION, CAL_CANT_ESTRELLAS
FROM STR_NOMBRE_GRUPO.USUARIO
JOIN STR_NOMBRE_GRUPO.PUBLICACION ON PUB_USU_ID=USU_ID
JOIN STR_NOMBRE_GRUPO.COMPRA ON COM_PUB_ID=PUB_ID
JOIN STR_NOMBRE_GRUPO.CALIFICACION ON COM_CAL_ID=CAL_ID
*/

/*
-- Calificaciones de subastas realizadas
SELECT USU_USERNAME,PUB_ID, PUB_FECHA_FINALIZACION, CAL_CANT_ESTRELLAS
FROM STR_NOMBRE_GRUPO.USUARIO
JOIN STR_NOMBRE_GRUPO.PUBLICACION ON PUB_USU_ID=USU_ID
JOIN STR_NOMBRE_GRUPO.OFERTA ON OFE_PUB_ID=PUB_ID
JOIN STR_NOMBRE_GRUPO.CALIFICACION ON OFE_CAL_ID=CAL_ID
*/

/* Compras clientes:
SELECT distinct USU_USERNAME, PUB_DESCRIPCION, COM_FECHA
FROM STR_NOMBRE_GRUPO.COMPRA
JOIN STR_NOMBRE_GRUPO.PUBLICACION ON COM_PUB_ID=PUB_ID
JOIN STR_NOMBRE_GRUPO.USUARIO ON USU_ID=COM_USU_ID
*/

/* Ofertas realizadas:
SELECT distinct USU_USERNAME, PUB_DESCRIPCION, OFE_FECHA, OFE_CAL_ID
FROM STR_NOMBRE_GRUPO.OFERTA
JOIN STR_NOMBRE_GRUPO.PUBLICACION ON OFE_PUB_ID=PUB_ID
JOIN STR_NOMBRE_GRUPO.USUARIO ON OFE_USU_ID=USU_ID
JOIN STR_NOMBRE_GRUPO.USUARIO ON USU_ID=OFE_USU_ID
WHERE OFE_CAL_ID is null
UNION
SELECT distinct USU_USERNAME, PUB_DESCRIPCION, OFE_FECHA, CAL_CANT_ESTRELLAS
FROM STR_NOMBRE_GRUPO.OFERTA
JOIN STR_NOMBRE_GRUPO.PUBLICACION ON OFE_PUB_ID=PUB_ID
JOIN STR_NOMBRE_GRUPO.USUARIO ON OFE_USU_ID=USU_ID
JOIN STR_NOMBRE_GRUPO.CALIFICACION ON CAL_ID=OFE_CAL_ID
JOIN STR_NOMBRE_GRUPO.USUARIO ON USU_ID=OFE_USU_ID
*/